[package]
name = "make-stream"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }
