[package]
name = "pathfinder-tagged-debug-derive"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
description = "Debug trait derive macro for pathfinder-tagged types"
repository = "https://github.com/eqlabs/pathfinder"
keywords = ["starknet", "derive", "debug", "proc-macro"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
