# Builds and uploads a P2P-enabled Docker image whenever triggered manually

name: Docker - P2P

on:
  workflow_dispatch:

env:
  # Workaround for https://github.com/rust-lang/cargo/issues/8719#issuecomment-1516492970
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  # Build a docker image unless this was triggered by a release.
  build-image-p2p:
    runs-on: pathfinder-large-ubuntu
    steps:
      - name: Determine Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: eqlabs/pathfinder
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate version
        id: generate_version
        run: |
          echo -n "pathfinder_version=" >> $GITHUB_OUTPUT
          git describe --tags --dirty >> $GITHUB_OUTPUT
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Required for git security reasons. See https://github.com/rustyhorde/vergen/pull/126#issuecomment-1201088162
      - name: Vergen git safe directory
        run: git config --global --add safe.directory /workspace
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
          file: ./Dockerfile
          build-args: |
            PATHFINDER_FORCE_VERSION=${{ steps.generate_version.outputs.pathfinder_version }}
            CARGO_EXTRA_ARGS=--features p2p
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            eqlabs/pathfinder:snapshot-p2p-${{ github.sha }}
            eqlabs/pathfinder:latest-p2p
          cache-from: type=gha
          cache-to: type=gha,mode=max
